### ISSUE TITLE
修正导入类的方法

### ISSUE THREAD

**Issue by peter-way** [sunpudding/python#9]
在测试代码中
```
# 导入AnalysisPcap.py
from TCP.PCAP.analysisPcap import *
```
这个运行不了。应该使用相对路径导入，应指明需要的类或函数，避免用 **\***。

这牵涉另一个文件结构的问题，我会另开一个 issue 。

**Comment by sunpudding** [comment]
调整目录结构后，重新导入类，for example：from analysispcap.analysisPcap import AnalysisPcap

**Comment by WANGxue708** [comment]
你好，有一些问题想请教一下，我现在在做流量分类之类的，想问一些问题。想问怎么得到你的私人联系方式呢？

**Comment by sunpudding** [comment]
你留下你的QQ号吧

**Comment by WANGxue708** [comment]
294421402。感谢感谢！




    
    
        
            
                
                    
                        
                    
                    
                        
                            xue WANG
                            
                            
                                
                                    邮箱：wxue708@gmail.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年12月16日 21:45，sunpudding 写道： 你留下你的QQ号吧

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sunpudding/python","title":"sunpudding/python","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sunpudding/python"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sunpudding in #9: 你留下你的QQ号吧"}],"action":{"name":"View Issue","url":"https://github.com/sunpudding/python/issues/9#issuecomment-447644594"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sunpudding/python/issues/9#issuecomment-447644594",
"url": "https://github.com/sunpudding/python/issues/9#issuecomment-447644594",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
